apiVersion: v1
kind: Service
metadata:
  name: traefik-service

spec:
  selector:
    app: traefik
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  - name: dashboard
    port: 8001
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer

---