apiVersion: v1 
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: dev 
spec:
  hard:
    pods: "20"
    requests.cpu: "4"
    requests.memory: 4Gi 
    limits.cpu: "10"
    limits.memory: 12Gi 