apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginxproxymanager-data-volume
  labels:
    type: local
  namespace: homelab
spec:
  claimRef:
    namespace: homelab
    name: nginxproxymanager-data-claim
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/nginxproxymanager/data"