apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginxproxymanager-data-claim
  namespace: homelab
spec:
  volumeName: nginxproxymanager-data-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi