# Copyright Joan Montas
# All rights reserved.
# License under GNU General Public License v3.0

---
- name: Install and configure suricata
  hosts: redhat
  become: true
  gather_facts: true
  tasks:

    - name: Gather Network Facts
      ansible.builtin.setup:
        gather_subset: network

    - name: Setup IP Netmask
      ansible.builtin.set_fact:
        ip: "{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.netmask }}"

    - name: Print the IP address
      ansible.builtin.debug:
        msg: "The IP address is: {{ ip }}"


    - name: Gather CIDR if IP Netmask- is present
      ansible.builtin.set_fact:
        mask_cidr: "{{ ip | ansible.utils.ipaddr('prefix') }}"
      when: ip is defined

    - name: Early terminate if Network Facts are not present
      ansible.builtin.assert:
        that: mask_cidr
        fail_msg: "The CIDR was not present"

    - name: Check if EPEL is already installed
      ansible.builtin.command: rpm -q epel-release
      register: epel_installed
      failed_when: false  # Avoid failure if package isn't found

    - name: Install EPEL
      when: epel_installed.rc != 0
      ansible.builtin.package:
        name: epel-release
        state: present

    # - name: Install pip
      # ansible.builtin.command: "sudo dnf install -y python3-pip"

    # - name: Install pexpect using pip
      # ansible.builtin.pip:
        # name: pexpect
        # state: present

    # - name: Enable Suricata stable repository using expect
      # ansible.builtin.expect:
        # command: sudo dnf copr enable @oisf/suricata-7.0
        # responses:
          # '.*': 'y'

    - name: Install Suricata
      ansible.builtin.package:
        name: suricata
        state: present

    - name: Enable Suricata service
      ansible.builtin.systemd:
        name: suricata
        enabled: true

    - name: Stop Suricata service
      ansible.builtin.systemd:
        name: suricata
        state: stopped

    - name: Replace af-packet to the default network interface
      ansible.builtin.replace:
        path: /etc/suricata/suricata.yaml
        regexp: '^(\s*)af-packet:\n(\s*)- interface: (.+)'
        replace: '\1af-packet:\n\2- interface: {{ ansible_default_ipv4.interface }}'

    - name: Replace af-packet to the default network interface
      ansible.builtin.replace:
        path: /etc/sysconfig/suricata
        regexp: 'OPTIONS="-i (.+)'
        replace: 'OPTIONS="-i {{ ansible_default_ipv4.interface }} --user suricata "'


    - name: Add live rule reloading support
      ansible.builtin.lineinfile:
        path: /etc/suricata/suricata.yaml
        line: "detect-engine:\n  - rule-reload: true"
        insertafter: EOF

    - name: Run suricata-update
      ansible.builtin.command: suricata-update

    - name: Start Suricata service
      ansible.builtin.systemd:
        name: suricata
        state: started

    - name: Add localfile for suricata
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/ossec.conf
        block: |
            <localfile>
              <log_format>json</log_format>
              <location>/var/log/suricata/eve.json</location>
            </localfile>
        marker: ""
        insertafter: "<something>\n(</localfile>\n)*"
