---

- hosts: CentOS_Agents
  become: true
  tasks:

    - name: Deleting Wazuh agent
      ansible.builtin.script: remove_agent_centos.sh
      register: value

    - name: Recording and printing the output 
      debug:
        var: value