
- name: "Configure Bad SSH"
  hosts: GROUP_ONE
  become: true
  vars:
    sshd_config: "/etc/ssh/sshd_config"
  tasks:
    - name: Enable remote root login
      lineinfile: 
        dest: "{{ sshd_config }}" 
        regexp: '^#?PermitRootLogin' 
        line: 'PermitRootLogin yes'
      notify: "Restart sshd"
      tags:
        - root
    - name: Disable password login
      lineinfile: 
        dest: "{{ sshd_config }}" 
        regexp: '^(#\s*)?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
      notify: "Restart sshd"

  handlers:
    - name: "Restart sshd"
      ansible.builtin.service:
        name: sshd
        state: restarted

- name: "Install Web Server"
  hosts: GROUP_WEB_SERVER
  become: true
  vars:
    web_server_title: "IaC Website"
  tasks:
    - name: "Install nginx"
      ansible.builtin.package:
        name: nginx
        state: present
    - name: "Enable nginx service"
      ansible.builtin.service:
        name: nginx
        enabled: true
    - name: "Copy nginx page"
      ansible.builtin.template:
        src: ./src/nginx/index.html
        dest: /var/www/html/index.html
      notify: "Restart nginx"
    - name: "Copy nginx config"
      ansible.builtin.copy:
        src: ./src/nginx/default
        dest: /etc/nginx/sites-available/default
      notify: "Restart nginx"

  handlers:
    - name: "Restart nginx"
      ansible.builtin.service:
        name: nginx
        state: restarted
