# This is if you are not using loadbalancer

apiVersion: v1 
kind: Service
metadata:
  name: nfs-server-service
  namespace: storage
spec:
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    app: nfs-server 