apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-main-volume
  labels:
    type: local
  namespace: storage
spec:
  claimRef:
    namespace: storage
    name: nfs-main-claim
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/nfs"