apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-main-claim
  namespace: storage
spec:
  volumeName: nfs-main-volume
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi