kind: Pod
apiVersion: v1
metadata:
  name: nfs-direct
  namespace: storage
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: data
      mountPath: /demo/data
  volumes:
  - name: data
    nfs:
      server: "10.100.203.162"
      path: "/pvc" # "nfs-direct" folder must exist inside "/exports" directory of NFS server