apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-app-claim
  namespace: storage
spec:
  volumeName: test-app-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi