apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-app-volume
  labels:
    type: local
  namespace: storage
spec:
  claimRef:
    namespace: storage
    name: test-app-claim
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "10.100.203.162"
    path: "/pvc"
  