version: '2'

services:

  wazuh:
    image: wazuh/wazuh
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    depends_on:
      - logstash


  filebeat:
    image: docker.elastic.co/beats/filebeat:6.7.1
    hostname: filebeat
    restart: always
    links:
      - logstash
    depends_on:
      - logstash
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./log:/var/log/suricata

  # logstash:
  #   # image: wazuh/wazuh-logstash
  #   # image: optimum/crm:wazuh-logstash
  #   image: optimum/crm:wazih_lohstash_dash
  #   hostname: logstash
  #   restart: always
  #   links:
  #     - elasticsearch:elasticsearch
  #   ports:
  #     - "5000:5000"
  #     - "5044:5044"
  #   depends_on:
  #     - elasticsearch
  #   volumes:
  #     - ./log:/var/log/suricata
  #     - ./synlite_suricata:/usr/share/logstash/synlite_suricata
  #     - ./jvm.options:/usr/share/logstash/config/jvm.options

  elasticsearch:
    #image: wazuh/wazuh-elasticsearch
    image: optimum/crm:wazuh-elastic-dash
    hostname: elasticsearch
    restart: always
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      - node.name=node-1
      - cluster.name=wazuh
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g

  kibana:
    # image: wazuh/wazuh-kibana
    image: optimum/crm:wazih_kibana_dash
    hostname: kibana
    restart: always
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh

  suricata:
    network_mode: host
    cap_add:
      - ALL
    privileged: true
    image: optimum/crm:suricata
    hostname: suricata
    restart: always
    depends_on:
      - logstash
    volumes:
      - ./log:/var/log/suricata
    entrypoint: /etc/entrypoint.sh
